Blog/urls.py
from django.urls import path,include
from django.views.generic import TemplateView

from . import views
from .views import PostCreate,UpdatePost,DeletePost,CategoryCreate,UpdateCategory,DeleteCategory,CreateTag,UpdateTag,DeleteTag,SiteSettings




app_name = 'Posts'
urlpatterns = [
	path("Welcome/", views.Welcome, name = "Welcome" ),
	path("Single/<int:pk>", views.Single, name = "Single" ),
	path("Category/<int:pk>", views.CategoryPage, name = "CategoryPage" ),
	path("Tag/<int:pk>", views.TagPage, name = "TagPage" ),
	path("Search/", views.Search, name = "Search" ),
	path("", views.ShowPosts, name = "ShowPosts" ),
	path("CreatePost/", PostCreate.as_view(), name = "CreatePost" ),
	path("UpdatePost/<int:pk>/", UpdatePost.as_view(), name = "UpdatePost" ),
	path("DeletePost/<int:pk>/", DeletePost.as_view(), name = "DeletePost" ),
	path("AddComment/<int:pk>/", views.AddComment, name = "AddComment" ),
	path("CommentApprove/<int:pk>/", views.CommentApprove, name = "CommentApprove" ),
	path("CommentRemove/<int:pk>/", views.CommentRemove, name = "CommentRemove" ),
	path("ShowCategories/", views.ShowCategories, name = "ShowCategories" ),
	path("CreateCategory/", CategoryCreate.as_view(), name = "CreateCategory" ),
	path("UpdateCategory/<int:pk>/", UpdateCategory.as_view(), name = "UpdateCategory" ),
	path("DeleteCategory/<int:pk>/", DeleteCategory.as_view(), name = "DeleteCategory" ),
	path("ShowTags/", views.ShowTags, name = "ShowTags" ),
	path("CreateTag/", CreateTag.as_view(), name = "CreateTag" ),
	path("UpdateTag/<int:pk>/", UpdateTag.as_view(), name = "UpdateTag" ),
	path("DeleteTag/<int:pk>/", DeleteTag.as_view(), name = "DeleteTag" ),
	path("Settings/<int:pk>", SiteSettings.as_view() , name = "SiteSettings" ),
	path("UserPage/", views.UserPage, name = "UserPage" ),
	path("DeactivateUser/<int:pk>", views.DeactivateUser, name = "DeactivateUser" ),
	path("MakeAdmin/<int:pk>", views.MakeAdmin, name = "MakeAdmin" ),
	path("Profile/<int:pk>", views.ProfileSettings, name = "ProfileSettings" ),
]

BlogInDjango/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	path("blog/", include("Blog.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'),),
    path('accounts/', include('accounts.urls')),
    path("summernote/", include( 'django_summernote.urls' )),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#ovo samo radi u debug modu i kada je media url localni ("/media")
#isto tako ovo govori lokalnom pc da priakzuje korisnicko uploadane filove

Blog/models.py
from django.db import models
from django.db.models.signals import post_save
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User


class Category( models.Model ):
	name = models.CharField( max_length = 255 )
	created_at = models.DateTimeField( auto_now_add = True )
	updated_at = models.DateTimeField( auto_now = True )
	#ovo nam koriste create viewovima kao succesurl kada su gotovi
	def get_absolute_url(self):
		return reverse("Posts:ShowCategories")

	def __str__( self ):
		return self.name


class Tag( models.Model ):
	name = models.CharField( max_length = 255 )
	created_at = models.DateTimeField( auto_now_add = True )
	updated_at = models.DateTimeField( auto_now = True )

	def get_absolute_url(self):
		return reverse("Posts:ShowTags")

	def __str__( self ):
		return self.name


class Post( models.Model ):
	user = models.ForeignKey( User, on_delete = models.CASCADE, null = True )
	category = models.ForeignKey( 'Category' , on_delete = models.CASCADE )
	tags = models.ManyToManyField( Tag )
	title = models.CharField( max_length = 255 )
	slug = models.SlugField( max_length = 255 )
	description = models.TextField()
	thumbnail = models.ImageField( upload_to = 'images', blank = True, null = True )
	created_at = models.DateTimeField( auto_now_add = True ) #ovako ce automatski napraviti datum kreacije
	updated_at = models.DateTimeField( auto_now = True )
	
	def get_absolute_url(self):
		return reverse("Posts:Welcome")

	def approved_comments(self):
		return self.comments.filter(approved_comments = True)

	def __str__( self ):	#ovo ce imenovat nas querry prema titlu da nije numerirano
		return self.title


class Settings( models.Model ):
	siteName = models.CharField( max_length = 255, default="test")
	contact_number = models.CharField( max_length = 255, default="000" )
	contact_address = models.CharField( max_length = 255, default="test" )
	email = models.EmailField( max_length = 255, default="test@test.com")
	created_at = models.DateTimeField( auto_now_add = True )
	updated_at = models.DateTimeField( auto_now = True )

	def get_absolute_url(self):
		return reverse("Posts:Welcome")

	def __str__( self ):
		return self.siteName


class Profile( models.Model ):
	user = models.OneToOneField( User, on_delete = models.CASCADE) #spajanje profile sa userom
	avatar = models.ImageField( upload_to = 'images', blank = True, default = "" )
	about = models.TextField( blank = True, default = "" )
	link = models.CharField( max_length = 255, blank = True, default = "" )
	created_at = models.DateTimeField( auto_now_add = True)
	updated_at = models.DateTimeField( auto_now = True)

def create_profile(sender, **kwargs):
	user = kwargs["instance"]
	if kwargs["created"]:
		user_profile = Profile(user = user)
		user_profile.save()
post_save.connect(create_profile, sender = User)


class Comment(models.Model):
	post = models.ForeignKey( Post, on_delete = models.CASCADE )
	author = models.CharField( max_length = 200 )
	text = models.TextField()
	created_at = models.DateTimeField( auto_now_add = True )
	approved_comment = models.BooleanField( default = False )

	def approved(self):
		self.approved_comment = True
		self.save()

	def __str__(self):
		return self.text

Blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse,reverse_lazy
from django.utils.text import slugify
from django.forms import Textarea
from django.core.exceptions import PermissionDenied
from django.forms.models import inlineformset_factory
from django import forms
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin #provjerava dali je user logiran prije nego sto pokrene view
from django.contrib.auth.models import User
from django.views.generic import TemplateView,ListView,DetailView
from django.views.generic.edit import FormView,CreateView,UpdateView,DeleteView

from .models import Post,Category,Tag,Settings,Profile,Comment
from .forms import PostForm,CategoryForm,TagForm,SettingsForm,UserForm,CommentForm


#----POST----
def ShowPosts(request):

	allPosts = Post.objects.all()
	return render(request, "Blog/Post/ShowPosts.html", {"allPosts":allPosts})

class PostCreate(LoginRequiredMixin, CreateView):
	model = Post
	form_class = PostForm
	template_name = "Blog/Post/CreatePost.html"
	
	#ovo napravi prije nego sto saveas
	def form_valid(self, form):
		# pospremi u Post.slug title koji ti je trenutno u formi
		form.instance.slug = slugify(form.instance.title)
		#uzmi id trenutnog logiranog usera
		user_id = self.request.user.id
		#dohavti querryset trenutno logirano usera
		user = User.objects.get(id = user_id )
		#savaj querry set u user filed od post modela( treba biti objekt a ne samo id )
		form.instance.user = user
		#save
		return super().form_valid(form)

	def get_context_data(self, **kwargs):
	    # prvo napravi context(dictonary) sa pozvimo base get_context
	    context = super().get_context_data(**kwargs)
	    # zatim u njega dodaj kljuc(var)
	    settings = Settings.objects.get(id = 1)
	    context['Settings'] = Settings.objects.get(id = 1)
	    #ovako izvuces trenutni objekt koji se editira
	    context['Title'] = settings.siteName
	    return context

class UpdatePost(UpdateView):
	model = Post
	form_class = PostForm
	template_name = "Blog/Post/EditPost.html"
	
	#ovo napravi prije nego sto saveas
	def form_valid(self, form):
		#tu pospremi u Post.slug title koji ti je tretno u formi
		form.instance.slug = slugify(form.instance.title)
		#save
		return super().form_valid(form)

	#get context data se izvrsava poslje get/post pa zato mozemo korstiti objekte iz requesta
	def get_context_data(self, **kwargs):
	    # prvo napravi context(dictonary) sa pozvimo base get_context
	    context = super().get_context_data(**kwargs)
	    # zatim u njega dodaj kljuc(var)
	    context['Settings'] = Settings.objects.get(id = 1)
	    #ovako izvuces trenutni objekt koji se editira
	    context['Title'] = self.object.title
	    return context

class DeletePost(DeleteView):
	model = Post
	success_url = reverse_lazy("Posts:Welcome")
	template_name = "Blog/Post/DeletePost.html"

	def get_context_data(self, **kwargs):
	    # prvo napravi context(dictonary) sa pozvimo base get_context
	    context = super().get_context_data(**kwargs)
	    # zatim u njega dodaj kljuc(var)
	    context['Settings'] = Settings.objects.get(id = 1)
	    return context
	#nauči kak post radi-----------------------------------
	def post(self, request, *args, **kwargs):
		#ako je Cancle u postu koju smo poslali(Cancle je ime buttona inputa)
		if "Cancel" in request.POST:
			#vrati natrag
			#get_object pretrazuje url kwargove za id
			PostID = self.get_object().id
			return redirect("Posts:Single", pk = PostID)
		else:
			#inace pokreni ispocetka deletePost clasu
			return super(DeletePost, self).post(request, *args, **kwargs)

#----COMMENT SECTION----
def AddComment(request,pk):
	post = Post.objects.get(pk = pk)
	if request.method == "POST":
		form = CommentForm(request.POST)
		if form.is_valid():
			comment = form.save(commit = False)
			comment.post = post
			comment.save()
			return redirect("Posts:Single", pk = post.pk)
	else:
		form = CommentForm()
	return render(request, 'Blog/Comments/index.html', { "form":form })

@login_required
def CommentApprove(request,pk):
	comment = Comment.objects.get(pk = pk)
	comment.approved()
	return redirect("Posts:Single", pk = comment.post.pk)

@login_required
def CommentRemove(request,pk):
	comment = Comment.objects.get(pk = pk)
	comment.delete()
	return redirect("Posts:Single", pk = comment.post.pk)


#----CATEGORY----
def ShowCategories(request):
	allCategories = Category.objects.all()
	settings = Settings.objects.get( id = 1 )
	Title = settings.siteName
	return render(request, "Blog/Category/ShowCategories.html", 
		{
			"allCategories":allCategories,
			"Settings":settings,
			"Title":Title,
		})

class CategoryCreate(LoginRequiredMixin, CreateView):
	model = Category
	form_class = CategoryForm
	template_name = "Blog/Category/CreateEditCategory.html"

	def get_context_data(self, **kwargs):
	    # prvo napravi context(dictonary) sa pozvimo base get_context
	    context = super().get_context_data(**kwargs)
	    # zatim u njega dodaj kljuc(var)
	    settings = Settings.objects.get(id = 1)
	    context['Settings'] = Settings.objects.get(id = 1)
	    #ovako izvuces trenutni objekt koji se editira
	    context['Title'] = settings.siteName
	    return context

class UpdateCategory(UpdateView):
	model = Category
	form_class = CategoryForm
	template_name = "Blog/Category/CreateEditCategory.html"

	def get_context_data(self, **kwargs):
	    # prvo napravi context(dictonary) sa pozvimo base get_context
	    context = super().get_context_data(**kwargs)
	    # zatim u njega dodaj kljuc(var)
	    context['Settings'] = Settings.objects.get(id = 1)
	    context['Title'] = self.object.name
	    return context

class DeleteCategory(DeleteView):
	model = Category
	success_url = reverse_lazy("Posts:ShowCategories")
	template_name = "Blog/Category/DeleteCategory.html"

	def get_context_data(self, **kwargs):
	    # prvo napravi context(dictonary) sa pozvimo base get_context
	    context = super().get_context_data(**kwargs)
	    # zatim u njega dodaj kljuc(var)
	    context['Settings'] = Settings.objects.get(id = 1)
	    #ovako izvuces trenutni objekt koji se editira
	    context['Title'] = self.object.name
	    return context

	def post(self, request, *args, **kwargs):
		#ako je Cancle u postu koju smo poslali(Cancle je ime buttona inputa)
		if "Cancel" in request.POST:
			#vrati natrag
			return HttpResponseRedirect("/blog/ShowCategories/")
		else:
			#inace pokreni ispocetka deletePost clasu
			return super(DeleteCategory, self).post(request, *args, **kwargs)


#----TAGS----
def ShowTags(request):
	settings = Settings.objects.get( id = 1 )
	Title = settings.siteName
	allTags = Tag.objects.all()
	return render(request, "Blog/Tag/ShowTags.html", 
		{
			"allTags" : allTags,
			"Settings":settings,
			"Title":Title,
		})

class CreateTag(LoginRequiredMixin, CreateView):
	model = Tag
	form_class = TagForm
	template_name = "Blog/Tag/CreateEditTag.html"

	def get_context_data(self, **kwargs):
	    # prvo napravi context(dictonary) sa pozvimo base get_context
	    context = super().get_context_data(**kwargs)
	    # zatim u njega dodaj kljuc(var)
	    settings = Settings.objects.get(id = 1)
	    context['Settings'] = Settings.objects.get(id = 1)
	    #ovako izvuces trenutni objekt koji se editira
	    context['Title'] = settings.siteName
	    return context

class UpdateTag(UpdateView):
	model = Tag
	form_class = TagForm
	template_name = "Blog/Category/CreateEditCategory.html"

	def get_context_data(self, **kwargs):
	    # prvo napravi context(dictonary) sa pozvimo base get_context
	    context = super().get_context_data(**kwargs)
	    # zatim u njega dodaj kljuc(var)
	    context['Settings'] = Settings.objects.get(id = 1)
	    context['Title'] = self.object.name
	    return context

class DeleteTag(DeleteView):
	model = Tag
	success_url = reverse_lazy("Posts:ShowTags")
	template_name = "Blog/Tag/DeleteTag.html"

	def get_context_data(self, **kwargs):
	    # prvo napravi context(dictonary) sa pozvimo base get_context
	    context = super().get_context_data(**kwargs)
	    # zatim u njega dodaj kljuc(var)
	    context['Settings'] = Settings.objects.get(id = 1)
	    #ovako izvuces trenutni objekt koji se editira
	    context['Title'] = self.object.name
	    return context

	def post(self, request, *args, **kwargs):
		#ako je Cancle u postu koju smo poslali(Cancle je ime buttona inputa)
		if "Cancel" in request.POST:
			#vrati natrag
			return HttpResponseRedirect("/blog/ShowTags/")
		else:
			#inace pokreni ispocetka deletePost clasu
			return super(DeleteTag, self).post(request, *args, **kwargs)


#----SETTINGS----
class SiteSettings(LoginRequiredMixin, UpdateView):
	model = Settings
	form_class = SettingsForm
	template_name = "Blog/Settings/index.html"

	def get_context_data(self, **kwargs):
	    # prvo napravi context(dictonary) sa pozvimo base get_context
	    context = super().get_context_data(**kwargs)
	    # zatim u njega dodaj kljuc(var)
	    context['Settings'] = Settings.objects.get(id = 1)
	    #ovako izvuces trenutni objekt koji se editira
	    context['Title'] = self.object.siteName
	    return context

			

#----USERS----
def UserPage(request):
	settings = Settings.objects.get(id = 1)
	Title = settings.siteName
	allUsers = User.objects.all() #User je djangov User model
	regUser = request.user

	return render(request, "Blog/User/index.html", 
		{
			"allUsers":allUsers, 
			"current_user":regUser,
			"Settings":settings,
			"Title":Title
		})

def MakeAdmin(request,pk):
	user = User.objects.get(id = pk)
	if request.user.is_staff == 1 and user.is_staff == True:
		user.is_staff = False
		user.save()
		return HttpResponseRedirect("/blog/UserPage/")
	elif request.user.is_staff == 1 and user.is_staff == False:
		user.is_staff = True
		user.save()
		return HttpResponseRedirect("/blog/UserPage/")
	else:
		raise PermissionDenied

def DeactivateUser(request,pk):

Blog/templates/Blog/Category.html
{% extends "Blog/Header.html" %}

{% block content %}
	<div class="container">
		<h1>{{ Category.name }}</h1>
		<hr>
	</div>
	<div class="container">
		<div class="row">
			{% for Post in Category.post_set.all %}
			<div class="col-lg-8 col-md-8 col-sm-8 Border">
				<div class = "Capitalize">
					<a class="Link" href="{% url 'Posts:Single' Post.id %}"><h4 class="Capitalize Title">{{ Post.title }}</h4></a>
				</div>
				<div class="PostInfo">
					<p style="margin: 0px;">Poste by: <strong class="Capitalize">{{ Post.user.username }}</strong></p>
					{% load humanize %}
					<p style="margin: 0px;">{{ Post.created_at|naturaltime }}</p>
				</div>
			</div>
			{% empty %}
			<div class="col">
				<p>There are curently no posts related to this category!</p>
			</div>
			{% endfor %}
		</div>
	</div>
{% endblock %}

Blog/templates/Blog/Header.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ Title }}</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styling.css' %}">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/frontEnd.css"> 
    <!--Font-->
    <link href="https://fonts.googleapis.com/css?family=Merriweather&display=swap" rel="stylesheet"> 

</head>

<body>
	<header>
		<div class="container-fluid">
			<div class="row">
				<div class="col">
					<nav class="navbar sticky-top navbar-light">
						<a class="navbar-brand" href="{% url 'Posts:Welcome' %}"><h2>{{ Settings.siteName }}</h2></a>
						<form class="form-inline" method="GET" action="{% url 'Posts:Search' %}">
							<input class="form-control mr-sm-2" type="text" name="Querry" placeholder="Search" arial-label="Search">
							<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
						</form>  
						<div id="NavbarLogin">
							<ul class="nav navbar-right">
								{% if user.is_authenticated  %}
								<p style="padding-top: 8px;">Welcome back <a href="{% url 'Posts:ProfileSettings' user.id %}" style="text-transform: capitalize;">{{user.username}}</a></p>
								<li class="nav-item">
									<a class="nav-link" href="{% url 'logout' %}">Log Out</a>
								</li>
								<div>
									<div class="dropdown">
					                	<button onclick="myFunction()" class="dropbtn btn btn-link Select">
					                		<div class="icon"></div>
					                		<div class="icon"></div>
					                		<div class="icon"></div>
					                	</button>
					                	<div id="myDropdown" class="dropdown-content">
					                    	<a href="{% url 'Posts:CreatePost'%}">Create a post</a>
											<a href="{% url 'Posts:CreateCategory'%}">Create a category</a>
											<a href="{% url 'Posts:CreateTag'%}">Create a tag</a>
											<a href="{% url 'Posts:ShowCategories'%}">Show all categories</a>
											<a href="{% url 'Posts:ShowTags'%}">Show all tags</a>
											{% if user.is_staff %}
												<a href="{% url 'Posts:UserPage' %}">Users</a>
												<a href="{% url 'Posts:SiteSettings' pk=1 %}">Settings</a>
											{% endif %}
					                	</div>
					                </div>
								</div>
								{% else %}
								<li class="nav-item">
									<a class="nav-link" href="{% url 'login' %}">Log In</a>
								</li>
								<li class="nav-item">
									<a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
								</li>
								{% endif %}
							</ul>
						</div>
					</nav>
				</div>
			</div>
		</div>
	</header>

	{% block content %}
	{% endblock %}


<!--scripts-->
{% load staticfiles %}
<script src="{% static 'js/dropdown.js' %}"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
</body>
</html>

Blog/templates/Blog/Search.html
{% extends "Blog/Header.html" %}

{% block content %}
	<div class="container">
		<h1>Search results for "{{ SearchQuerry }}"</h1>
		<hr>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-md-8 col-sm-8">
				{% for Result in Search %}
					<div class="row Border">
						<div class="col">
							<div class="Capitalize">
								<a class="Link" href="{% url 'Posts:Single' Result.id %}"><h4 class="Title">{{ Result.title }}</h4></a>
							</div>
							<div class="PostInfo">
								<p style="margin: 0px;">Posted by <strong class="Capitalize">{{ Result.user.username }}</strong></p>
								{% load humanize %}
								<p style="margin: 0px;">{{ Result.created_at|naturaltime }}</p>
							</div>
						</div>
					</div>
				{% empty %}
					<div class="col">
						<p>Try a different search term!</p>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}

Blog/templates/Blog/Single.html
{% extends "Blog/Header.html" %}

{% block content %}
	<div class="container" style="margin-top: 40px;">
		<div class="row ">
			<div class="col-lg-8 col-md-8">
				<div id="Title">
					<h1>{{ Post.title }}</h1>
				</div>
			</div>
			<div class="col-lg-4 col-md-4" style="text-align: right;">
				{% if User.id == Post.user.id %}
					<a class="btn btn-primary" href="{% url 'Posts:UpdatePost' Post.id %}">Edit</a>
					<a class="btn btn-danger" href="{% url 'Posts:DeletePost' Post.id %}">Delete</a>
				{% endif %}
			</div>
		</div>
		<div class="row">
			<div class="col-lg-1 col-md-1">
				{% if not Post.user.profile.avatar %}
				{% else %}
				<div>
					<img src="{{ Post.user.profile.avatar.url }}" height="50" width="50" style="border-radius: 50%;">
				</div>
				{% endif %}
			</div>
			<div class="col-lg-4 col-md-4">
				<div class="Spacing" style="text-align: left;">
					<p style="margin: 0px;" class="Capitalize">{{ Post.user.username }}</p>
					{% load humanize %}
					<p style="margin: 0px;">{{ Post.created_at|naturaltime }}</p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col">
				{% if not Post.thumbnail  %}
				<div>
					
				</div>
				{% else %}
				<div>
					<img src="{{ Post.thumbnail.url }}" class="Image">
				</div>
				{% endif %}
			</div>
		</div>
		<div class="row">
			<div class="col">
				<div class="Description">
					<p>{{Post.description|safe}}</p>
				</div>
			</div>
		</div>
	</div>
	<div class="container">
		<nav>
			<ul class="nav">
			{% for Tag in Post.tags.all %}
				<li class="nav-item">
					<a class="nav-link Tags Link" href="{% url 'Posts:TagPage' Tag.id %}">{{ Tag.name }}</a>
				</li>
			{% endfor %}
		</ul>
		</nav>
	<hr>
	</div>
	<div class="container">
		<div class="row">
			<div class="col">
				<div>
					<h3>Comment to the post</h3>
				</div>
			</div>
			<div class="col">
				<div style="text-align: right;">
					<a class="btn btn-primary" href="{% url 'Posts:AddComment' Post.id %}">Add Comment</a>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-2"></div>
			<div class="col-lg-8">
				<hr>
				{% for comment in Post.comment_set.all %}
					{% if user.is_authenticated or comment.approved_comment %}
					<div>
						<div>
							{{ comment.created_at }}
							{% if not comment.approved_comment %}
								<a class="btn btn-primary" href="{% url 'Posts:CommentApprove' pk=comment.id %}">Approve</a>
								<a class="btn btn-primary" href="{% url 'Posts:CommentRemove' pk=comment.id %}">Delete</a>
							{% endif %}
						</div>
						<p><strong class="Capitalize">{{ comment.author }}</strong></p>
						<p>{{ comment.text|safe }}</p>
						<hr>
					</div>
					{% endif %}
				{% empty %}
					<p>Be the first to comment</p>
				{% endfor %}
			</div>
			<div class="col-lg-2"></div>
		</div>
	</div>
	<footer>
	    <div class="container" style="margin-top: 40px;">
	        <div class="row">
	            <div class="col-lg-6 col-lg-offset-3">
	                <div>
	                    <h3>{{Settings.siteName}}</h3>
	                </div>
	            </div>
	        </div>
	        <hr style="border-top: 1px solid white;">
	        <div class="row">
	            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
	                <div>
	                	<p>Mon-Fri 9am-6pm</p>
	                    <a href="#">{{Settings.contact_number}}</a>
	                </div>
	            </div>
	            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
	                <div>
	                	<p>Online support</p>
	                    <a href="#">{{Settings.email}}</a>
	                </div>            
	            </div>
	            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
	                <div>
	                    <a href="">{{Settings.contact_address}}</a>
	                </div>
	            </div>
	        </div>
	    </div>
	</footer>
		
{% endblock %}